name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Application/**'
      - 'docs/wiki/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '3.1.x'
   
    - name: build-application
      run: dotnet build ./src/Application/Application.sln
      
    - name: build-changelog
      run: git log > docs/wiki/iVendi.Stock-changelog.md
    
    - name: wiki-page-creator-action
      uses: Decathlon/wiki-page-creator-action@v2.0.0
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        ACTION_MAIL: laura.armitage@ivendi.com
        ACTION_NAME: lauraivendi
        OWNER: lauraivendi
        REPO_NAME: test-wiki-docs
        MD_FOLDER: docs/wiki
        
